### ISSUE TITLE
Column header display issue

### ISSUE THREAD

**Issue by limodou** [crisward/riot-grid2#1]
![image](https://cloud.githubusercontent.com/assets/116544/16473135/21d0b292-3e9d-11e6-8050-10dee7fbb152.png)

You can see header is not aligned with column below.

**Comment by crisward** [comment]
Thank, I know. It's still in active development (though not as active as I'd like).

It's caused by allowing for the scroll bar in the main content area. I added a 15px margin right in the header which fixes this for mac's but it should really measure the sizes before applying this margin to allow for different size scroll bars.

Thanks for reporting it though, I'll update this when I've had chance to fix it.

**Comment by crisward** [comment]
Just updated the scroll logic to fix the mobile issue. Can you let me know if the above still happens (seems to be ok on mine now).

Thanks.
