### ISSUE TITLE
Horizontal scroll bar goes across the fixed columns

### ISSUE THREAD

**Issue by ronen** [crisward/riot-grid2#18]
Somewhat niggling, but I notice that the horizontal scrollbar (which appears when scrolling, on OS X) spans the full width of the grid, including fixed columns.   That can be seen, e.g., in [your demo](http://crisward.github.io/riot-grid2/).

IMHO the UX look & feel of that is a bit off, it seems like the scroll bar should span just the scrollable region.

I haven't looked into addressing it at all.  I imagine the solution would be to have the scrolling overlay only cover the non-fixed columns.   That'd also mean that (unlike current behavior) you couldn't scroll horizontally with the cursor over the fixed columns, but I think that's actually acceptable UX.   And of course would need to do whatever's needed so that vertical scrolling would still work on the fixed columns.

What do you think?

**Comment by crisward** [comment]
I kind of agree, and that is how it was originally programmed. However my users complained it didn't work because their vertical scrolls didn't work over the fixed columns. Also react fixed table works with the fixed cells scrollable and I imagine they've done even more user testing than me.

I'd like to find a more customisable way of listening for scroll events, that allows you to interact with the content below, but until I do the current solution is probably the best for users/performance.

**Comment by ronen** [comment]
It occurred to me that it ought to be possible to get vertical scrolling on the fixed columns and horizontal+vertical scrolling on the non-fixed columns, by having two overlays.    Tried it out and it seemed to work...

**Comment by crisward** [comment]
I've achieved the same effect while reworking the scroll system to work with hover events etc. The overlay now doesn't receive any events and is just there for the scroll bars. There are still a couple of issues which I'll raise separately. Thanks for your help on this.

**Comment by ronen** [comment]
cool, even better!  I'll try it out when I get a chance.
