### ISSUE TITLE
Demo is faulty

### ISSUE THREAD

**Issue by KempWatson** [crisward/riot-grid2#26]
...says 100,000 rows, there are only 10,000.

**Comment by crisward** [comment]
I know... reduced it a while ago. The grid is fine with 100,000 rows, but I generate the js array locally and that gave the impression it takes a long time to load, because it was a blocking process. Like many other data grid implementations, it only renders visible rows so in theory would be fine with any number (as long as they fit in memory). I'll update the read me.

**Comment by KempWatson** [comment]
Thanks. Works well - I sounded snarky upon a re-read, my apologies, wasn't
meant to be...

Is it possible to have non-fixed width columns? I know it's a bit
problematic when scrolling, if the columns adjust size on new data coming
into view... but is it possible with the control? Ideally I'd like the
columns to attempt to best-fit a responsive table width.

Thanks, K. Watson
